### ISSUE TITLE
Idls RPMs

### ISSUE THREAD

**Issue by cvalenzu** [LeoXDXp/acs-rpm#2]
- [x] acserridl
- [x] acsidlcommon
- [x] loggingidl
- [x] acscomponentidl
- [ ] cdbidl
- [ ] maciidl
- [x] baciidl
- [ ] acsncidl
- [ ] acsalarmidl
- [ ] acsdaemonidl
- [ ] XmlIdl

**Comment by cvalenzu** [comment]
- loggingidl (410d9cf70fee586673c78aecdf67c1c876d4f37d), 
- acserridl (8beb78dad1975fa86ac7c6ae60cfbdbd2e3a5741),
- baciidl (71860ffc85a77bbf06bcfe366405a6c585177cfa)
- maciidl (6a654cb67fb01f91f5b89efa928cdd2)
- acscomponentidl (abbe5694d)
- acsidlcommon (ff32d81f5ab59388956bc4a327420dae3fd41)

Update details on this and the rest of the packages at https://csrg-utfsm.github.io/

**Comment by sirspock** [comment]
Bye bye
