### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by mosoriob** [LeoXDXp/acs-rpm#3]
Package: ACS-acserr-1-2017.02-1.el7.centos.x86_64
Description: The binary /usr/local/bin/acserrGenJava doesn't have execution permissions.
```
[acs.node3@builder rpmbuild]$ acserrGenJava
-bash: /usr/local/bin/acserrGenJava: Permission denied
```

**Comment by LeoXDXp** [comment]
Fixed on 3f5f773e2bf2c7e5461566a92f224fcf94b02bb5. :smile:
